security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Acme\Bundle\ApiBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

#    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: password, roles: [ 'ROLE_USER' ] }
#                    admin: { password: password, roles: [ 'ROLE_ADMIN' ] }

    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    user:  { password: password, roles: [ 'ROLE_USER' ] }
                    admin: { password: password, roles: [ 'ROLE_ADMIN' ] }
        user_db:
            entity: { class: Acme\Bundle\ApiBundle\Entity\User, property: email }

    firewalls:
        dev:
            pattern:  ^/api/(_(profiler|wdt|doc))/
            security: false

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path: /api/login_check
                require_previous_session: false
                username_parameter: username
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                provider: chain_provider

        api:
            pattern:   ^/api
            stateless: true
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    name:    bearer

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
