parameters:
    acme_api.event.jwt_response_listener.class: Acme\Bundle\ApiBundle\EventListener\JWTResponseListener

services:
    acme_api.event.jwt_response_listener:
        class: %acme_api.event.jwt_response_listener.class%
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
